#!/bin/sh
# Check for secrets in staged files
staged_files=$(git diff --name-only --cached --diff-filter=ACMR)
if [ -n "$staged_files" ]; then
  echo "$staged_files" | xargs npx secretlint
fi

# Run all linters (SEO + Code)
# Strict lint-staged only
npx lint-staged
